name: Deploy to Render

on:
  push:
    branches: [despliegue_render_v3]

jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: Bounceapp/render-action@0.8.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.TOKEN_GITHUB }}
          service-id: ${{secrets.RENDER_SERVICE_ID}}
          retries: 10
          wait: 16000
          sleep: 30000