name: Deploy to Render

on:
  push:
    branches: [despliegue_render_v3]

jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{secrets.RENDER_TOKEN}}
          github-token: ${{secrets.TOKEN_GITHUB}}
          service-id: srv-cq4cicg8fa8c73fncir0?key=7WlubphvIcE
          retries: 20
          wait: 16000
          sleep: 30000